<a href="https://colab.research.google.com/github/Adnner-Esperilla-DEV/Programacion_101/blob/main/Examen3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


ADNNER ESPERILLA RUIZ
# Pregunta 1:

a) Crea un array unidimensional que contenga los números primos entre 1 y 50.
b) Convierte el array unidimensional anterior en una matriz de forma (n, 2), donde n es el número adecuado de
filas. Si es necesario, agrega ceros al final del array para completar la matriz.
c) Calcula la suma de cada fila y crea un nuevo array que contenga estos valores.

In [ ]:
import numpy as np

def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

primes = [num for num in range(2, 51) if is_prime(num)]
prime_array = np.array(primes)

num_primes = len(prime_array)
n = (num_primes + 1) // 2

matrix = np.zeros((n, 2), dtype=int)

padded_primes = np.zeros(n * 2, dtype=int)
padded_primes[:num_primes] = prime_array

matrix = padded_primes.reshape(n, 2)

row_sums = np.sum(matrix, axis=1)

print("Array de num primos:",prime_array )
print("\nMatriz (n,2):\n", matrix)
print("\nSuma de Filas:", row_sums)

Prime numbers array: [ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47]

Matrix of shape (n,2):
 [[ 2  3]
 [ 5  7]
 [11 13]
 [17 19]
 [23 29]
 [31 37]
 [41 43]
 [47  0]]

Sum of each row: [ 5 12 24 36 52 68 84 47]



Pregunta 2:
a) Crea un array bidimensional de forma (4, 4) que contenga números enteros aleatorios entre 1 y 100.
b) Cambia el tipo de datos del array a float64 y divide todos los elementos por 3.7.
c) Calcula y muestra las siguientes propiedades del array resultante:
● Dimensiones (ndim)
● Forma (shape)
● Tamaño total (size)
● Tipo de datos (dtype)

In [ ]:
import numpy as np

array = np.random.randint(1, 101, size=(4, 4))

array_float = array.astype(np.float64) / 3.7

print("Array bidimensional original:\n", array)
print("\nArray bidimensional modificado:\n", array_float)
print("\nDimensiones:", array_float.ndim)
print("Forma:", array_float.shape)
print("Tamaño total:", array_float.size)
print("Tipo de datos:", array_float.dtype)

Array bidimensional original:
 [[64 16 76 47]
 [20 10 55 13]
 [40 35 77 55]
 [17 70 46 26]]

Array bidimensional modificado:
 [[17.2972973   4.32432432 20.54054054 12.7027027 ]
 [ 5.40540541  2.7027027  14.86486486  3.51351351]
 [10.81081081  9.45945946 20.81081081 14.86486486]
 [ 4.59459459 18.91891892 12.43243243  7.02702703]]

Dimensiones: 2
Forma: (4, 4)
Tamaño total: 16
Tipo de datos: float64


Pregunta 3:
a) Crea un array x que contenga 100 valores equiespaciados entre -10 y 10.
b) Calcula el valor de la función f(x)=e**(-x**2) para cada elemento de x.
c) Encuentra el valor máximo y mínimo de f(x) y las posiciones en el array donde ocurren.

In [3]:
import numpy as np

x = np.linspace(-10, 10, 100)

fx = np.exp(-x**2)

valor_maximo = np.max(fx)
posicion_maximo = np.argmax(fx)
valor_minimo = np.min(fx)
posicion_minimo = np.argmin(fx)

print("Array x:\n", x)
print("\nFunción f(x):\n", fx)
print("\nValor máximo de f(x):", valor_maximo)
print("Posición del valor máximo:", posicion_maximo)
print("Valor mínimo de f(x):", valor_minimo)
print("Posición del valor mínimo:", posicion_minimo)

Array x:
 [-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919
  -8.98989899  -8.78787879  -8.58585859  -8.38383838  -8.18181818
  -7.97979798  -7.77777778  -7.57575758  -7.37373737  -7.17171717
  -6.96969697  -6.76767677  -6.56565657  -6.36363636  -6.16161616
  -5.95959596  -5.75757576  -5.55555556  -5.35353535  -5.15151515
  -4.94949495  -4.74747475  -4.54545455  -4.34343434  -4.14141414
  -3.93939394  -3.73737374  -3.53535354  -3.33333333  -3.13131313
  -2.92929293  -2.72727273  -2.52525253  -2.32323232  -2.12121212
  -1.91919192  -1.71717172  -1.51515152  -1.31313131  -1.11111111
  -0.90909091  -0.70707071  -0.50505051  -0.3030303   -0.1010101
   0.1010101    0.3030303    0.50505051   0.70707071   0.90909091
   1.11111111   1.31313131   1.51515152   1.71717172   1.91919192
   2.12121212   2.32323232   2.52525253   2.72727273   2.92929293
   3.13131313   3.33333333   3.53535354   3.73737374   3.93939394
   4.14141414   4.34343434   4.54545455   4.74747475   4.94949495
 

Dado el siguiente array bidimensional:
array = np.arange(1, 101).reshape(10, 10)
a) Extrae un subarray que contenga los elementos en posiciones pares de filas y columnas (es decir, filas y
columnas con índices 0, 2, 4, 6, 8).
b) Reemplaza todos los elementos que son múltiplos de 3 por -1.
c) Utiliza indexación avanzada para extraer todos los números primos del array original y crea un nuevo array
con estos valores.


In [6]:
import numpy as np

array = np.arange(1, 101).reshape(10, 10)

subarray = array[::2, ::2]
print("Subarray con posiciones pares:\n", subarray)

array[array % 3 == 0] = -1
print("\nArray con múltiplos de 3 reemplazados por -1:\n", array)

def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

replace_prime = np.array([i for i in range(1,101) if is_prime(i)]) -1
prime_numbers = array.flatten()[replace_prime]

prime_array = np.array([num for num in prime_numbers if num != -1 and num > 0])

print("\nNúmeros primos del array original:\n", prime_array)

Subarray con posiciones pares:
 [[ 1  3  5  7  9]
 [21 23 25 27 29]
 [41 43 45 47 49]
 [61 63 65 67 69]
 [81 83 85 87 89]]

Array con múltiplos de 3 reemplazados por -1:
 [[  1   2  -1   4   5  -1   7   8  -1  10]
 [ 11  -1  13  14  -1  16  17  -1  19  20]
 [ -1  22  23  -1  25  26  -1  28  29  -1]
 [ 31  32  -1  34  35  -1  37  38  -1  40]
 [ 41  -1  43  44  -1  46  47  -1  49  50]
 [ -1  52  53  -1  55  56  -1  58  59  -1]
 [ 61  62  -1  64  65  -1  67  68  -1  70]
 [ 71  -1  73  74  -1  76  77  -1  79  80]
 [ -1  82  83  -1  85  86  -1  88  89  -1]
 [ 91  92  -1  94  95  -1  97  98  -1 100]]

Números primos del array original:
 [ 2  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97]


Pregunta 5:
a) Crea tres arrays unidimensionales de longitud 5 con números aleatorios entre 0 y 1.
b) Combina estos arrays para formar una matriz de forma (5, 3).
c) Agrega una columna de unos al principio de la matriz resultante, obteniendo una matriz de forma (5, 4).
d) Reordena las columnas de la matriz para que la columna de unos esté al final.


In [18]:
import numpy as np

array1 = np.random.rand(5)
array2 = np.random.rand(5)
array3 = np.random.rand(5)
print("\nNúmeros primos del array original:\n", array3)
matrix = np.column_stack((array1, array2, array3))

ones_column = np.ones((5, 1))
matrix = np.hstack((ones_column, matrix))

# d) Reordena las columnas de la matriz para que la columna de unos esté al final.
matrix = np.concatenate((matrix[:, 1:], matrix[:, :1]), axis=1)
print(matrix)



Números primos del array original:
 [0.58255899 0.76689529 0.8405205  0.18003162 0.52372545]
[[0.20028076 0.70579981 0.58255899 1.        ]
 [0.59995044 0.29359312 0.76689529 1.        ]
 [0.51026278 0.5142807  0.8405205  1.        ]
 [0.38032911 0.81273661 0.18003162 1.        ]
 [0.26608439 0.51997609 0.52372545 1.        ]]


Pregunta 6:

a) Crea una matriz simétrica positiva definida de tamaño 3x3.
b) Calcula sus valores y vectores propios (eigenvalores y eigenvectores).
c) Verifica que la multiplicación de la matriz original por un vector propio es igual al producto del eigenvalor
correspondiente por el vector propio.


In [22]:

import numpy as np


matriz = np.random.rand(3, 3)
matriz = np.dot(matriz, matriz.transpose())

matriz += 0.1 * np.eye(3)

print("Matriz simtrica", matriz)

eigenvalues, eigenvectors = np.linalg.eig(matriz)

print("\nEigenvalores:\n", eigenvalues)
print("\nEigenvectores:\n", eigenvectors)


for i in range(3):
    eigenvector = eigenvectors[:, i]
    result1 = np.dot(matriz, eigenvector)
    result2 = eigenvalues[i] * eigenvector
    print(f"\nVerificacion para el eigenvector {i+1}:")
    print("matriz* v =", result1)
    print("lambda * v =", result2)
    print("Son iguales?", np.allclose(result1, result2))

Matriz simtrica [[1.5658477  1.32145982 1.63855553]
 [1.32145982 1.52936773 1.5286568 ]
 [1.63855553 1.5286568  2.00691409]]

Eigenvalores:
 [4.71955712 0.13224226 0.25033013]

Eigenvectores:
 [[-0.55508794 -0.72197103  0.41308014]
 [-0.53508706 -0.07027823 -0.84186864]
 [-0.63683532  0.68834497  0.34730676]]

Verificacion para el eigenvector 1:
matriz* v = [-2.61976925 -2.52537392 -3.00558065]
lambda * v = [-2.61976925 -2.52537392 -3.00558065]
Son iguales? True

Verificacion para el eigenvector 2:
matriz* v = [-0.09547508 -0.00929375  0.09102829]
lambda * v = [-0.09547508 -0.00929375  0.09102829]
Son iguales? True

Verificacion para el eigenvector 3:
matriz* v = [ 0.10340641 -0.21074509  0.08694134]
lambda * v = [ 0.10340641 -0.21074509  0.08694134]
Son iguales? True


Pregunta 7:
a) Construye un sistema de ecuaciones lineales con tres ecuaciones y tres incógnitas donde la matriz de
coeficientes es singular (no invertible).
b) Intenta resolver el sistema utilizando np.linalg.solve() y explica el resultado obtenido.


In [25]:

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([1, 2, 3])

try:
    x = np.linalg.solve(A, B)
    print("Solución del sistema:", x)
except np.linalg.LinAlgError as e:
    print("Error al resolver el sistema:", e)
    print("La matriz de coeficientes es singular, por lo que no existe una solución única.")

Error al resolver el sistema: Singular matrix
La matriz de coeficientes es singular, por lo que no existe una solución única.


Pregunta 8
a) Crea un array de forma (4, 4, 4) con números enteros aleatorios entre 0 y 100.
b) Calcula la suma a lo largo del eje 0, obteniendo un array de forma (4, 4).
c) Calcula el promedio a lo largo del eje 1, obteniendo un array de forma (4, 4).
d) Reestructura el array original en una nueva forma de (8, 8) sin perder datos.


In [28]:
import numpy as np
array_3d = np.random.randint(0, 101, size=(4, 4, 4))

sum_along_axis_0 = np.sum(array_3d, axis=0)

average_along_axis_1 = np.mean(array_3d, axis=1)

reshaped_array = array_3d.reshape(8, 8)

print("Array (4, 4, 4):\n", array_3d)
print("\nSuma en eje 0 (4, 4):\n", sum_along_axis_0)
print("\nPromedio en eje 1 (4, 4):\n", average_along_axis_1)
print("\nArray  (8, 8):\n", reshaped_array)

Array (4, 4, 4):
 [[[ 49  47  10  99]
  [ 54  66  30  55]
  [ 77  23 100  98]
  [ 13  83  32  79]]

 [[ 52  92  27  11]
  [ 70  52  86 100]
  [ 31  27  49  48]
  [ 81  85 100  51]]

 [[ 65   1  18  56]
  [ 85   7  31  78]
  [ 63  16  46  50]
  [ 62  92  36  40]]

 [[ 14  82  82   9]
  [ 35  40  32   0]
  [ 26  70  94  48]
  [ 91  13  25  89]]]

Suma en eje 0 (4, 4):
 [[180 222 137 175]
 [244 165 179 233]
 [197 136 289 244]
 [247 273 193 259]]

Promedio en eje 1 (4, 4):
 [[48.25 54.75 43.   82.75]
 [58.5  64.   65.5  52.5 ]
 [68.75 29.   32.75 56.  ]
 [41.5  51.25 58.25 36.5 ]]

Array  (8, 8):
 [[ 49  47  10  99  54  66  30  55]
 [ 77  23 100  98  13  83  32  79]
 [ 52  92  27  11  70  52  86 100]
 [ 31  27  49  48  81  85 100  51]
 [ 65   1  18  56  85   7  31  78]
 [ 63  16  46  50  62  92  36  40]
 [ 14  82  82   9  35  40  32   0]
 [ 26  70  94  48  91  13  25  89]]


Pregunta 9:
Se define una secuencia de números donde cada elemento es el factorial del índice correspondiente.

a) Usando NumPy, crea un array que contenga los primeros 10 elementos de esta secuencia sin utilizar bucles
explícitos.
b) Calcula la suma de todos los elementos del array creado.
c) Dado que los factoriales pueden ser números muy grandes, cambia el tipo de datos del array a object para
manejar enteros arbitrariamente grandes y recalcula la suma

In [42]:
import numpy as np
import math
# Crear un array con los factoriales del 1 al 10
factoriales = np.array([math.factorial(n) for n in range(1, 11)])
print("Array de factoriales:", factoriales)
# Calcular la suma de los elementos
suma_factoriales = np.sum(factoriales)
print("Suma de los factoriales:", suma_factoriales)


# Cambiar el tipo de dato del array a object
factoriales_obj = factoriales.astype(object)

# Calcular nuevamente la suma con enteros grandes
suma_factoriales_obj = np.sum(factoriales_obj)
print("Suma de los factoriales con tipo object:", suma_factoriales_obj)


Array de factoriales: [      1       2       6      24     120     720    5040   40320  362880
 3628800]
Suma de los factoriales: 4037913
Suma de los factoriales con tipo object: 4037913


Pregunta 10:
a) Simula un conjunto de datos que represente las alturas (en cm) de 500 personas, siguiendo una distribución
normal con media 170 y desviación estándar 10.
c) Encuentra cuántas personas miden más de 180 cm y menos de 160 cm.
d) Normaliza los datos de altura para que tengan media 0 y desviación estándar

In [46]:
import numpy as np

media = 170
desviacion_estandar = 10
num_personas = 500

alturas = np.random.normal(media, desviacion_estandar, num_personas)
print("Primeras 10 alturas simuladas:", alturas[:10])
mas_de_180 = np.sum(alturas > 180)

menos_de_160 = np.sum(alturas < 160)

print(f"Personas que miden ms de 180 cm: {mas_de_180}")
print(f"Personas que miden menos de 160 cm: {menos_de_160}")
alturas_normalizadas = (alturas - np.mean(alturas)) / np.std(alturas)
print("Media de datos normalizados:", np.mean(alturas_normalizadas))
print("Desviación estándar de datos normalizados:", np.std(alturas_normalizadas))

Primeras 10 alturas simuladas: [177.61812121 156.60015895 169.73917427 166.32277457 176.96548114
 183.39780344 161.65108982 187.25591302 164.47922869 180.67890427]
Personas que miden ms de 180 cm: 95
Personas que miden menos de 160 cm: 65
Media de datos normalizados: 1.637801005927031e-15
Desviación estándar de datos normalizados: 1.0
