<a href="https://colab.research.google.com/github/Adnner-Esperilla-DEV/Programacion_101/blob/main/Examen3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pregunta 1:

a) Crea un array unidimensional que contenga los números primos entre 1 y 50.
b) Convierte el array unidimensional anterior en una matriz de forma (n, 2), donde n es el número adecuado de
filas. Si es necesario, agrega ceros al final del array para completar la matriz.
c) Calcula la suma de cada fila y crea un nuevo array que contenga estos valores.

In [4]:
import numpy as np

def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

primes = [num for num in range(2, 51) if is_prime(num)]
prime_array = np.array(primes)

num_primes = len(prime_array)
n = (num_primes + 1) // 2

matrix = np.zeros((n, 2), dtype=int)

padded_primes = np.zeros(n * 2, dtype=int)
padded_primes[:num_primes] = prime_array

matrix = padded_primes.reshape(n, 2)

row_sums = np.sum(matrix, axis=1)

print("Array de num primos:",prime_array )
print("\nMatriz (n,2):\n", matrix)
print("\nSuma de Filas:", row_sums)

Prime numbers array: [ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47]

Matrix of shape (n,2):
 [[ 2  3]
 [ 5  7]
 [11 13]
 [17 19]
 [23 29]
 [31 37]
 [41 43]
 [47  0]]

Sum of each row: [ 5 12 24 36 52 68 84 47]



Pregunta 2:
a) Crea un array bidimensional de forma (4, 4) que contenga números enteros aleatorios entre 1 y 100.
b) Cambia el tipo de datos del array a float64 y divide todos los elementos por 3.7.
c) Calcula y muestra las siguientes propiedades del array resultante:
● Dimensiones (ndim)
● Forma (shape)
● Tamaño total (size)
● Tipo de datos (dtype)

In [5]:
import numpy as np

array = np.random.randint(1, 101, size=(4, 4))

array_float = array.astype(np.float64) / 3.7

print("Array bidimensional original:\n", array)
print("\nArray bidimensional modificado:\n", array_float)
print("\nDimensiones:", array_float.ndim)
print("Forma:", array_float.shape)
print("Tamaño total:", array_float.size)
print("Tipo de datos:", array_float.dtype)

Array bidimensional original:
 [[64 16 76 47]
 [20 10 55 13]
 [40 35 77 55]
 [17 70 46 26]]

Array bidimensional modificado:
 [[17.2972973   4.32432432 20.54054054 12.7027027 ]
 [ 5.40540541  2.7027027  14.86486486  3.51351351]
 [10.81081081  9.45945946 20.81081081 14.86486486]
 [ 4.59459459 18.91891892 12.43243243  7.02702703]]

Dimensiones: 2
Forma: (4, 4)
Tamaño total: 16
Tipo de datos: float64
