<a href="https://colab.research.google.com/github/Adnner-Esperilla-DEV/Programacion_101/blob/main/01_Introduccion_a_Python/03_Estructuras_de_datos_parte2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


<h1 align=center><font size = 5>ESTRUCTURAS DE DATOS - PARTE 2
</font></h1>

---


**Tabla de Contenidos**

- Diccionarios
- Sets
- Matrices

---

## 1. Diccionarios

**Concepto:**

Un diccionario es una estructura de datos que almacena pares clave-valor. Las claves deben ser únicas y se utilizan para acceder a los valores asociados.

### Ejemplo 1.1: Creación de Diccionarios y Acceso a Elementos


In [9]:
# Crear un diccionario
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
print(persona)

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}


In [10]:
# Acceder a un valor
print("Nombre:", persona['nombre'])
print("Ciudad:", persona.get('ciudad'))


Nombre: Ana
Ciudad: Lima


In [11]:

# Añadir un nuevo par clave-valor
persona['profesion'] = 'Ingeniera'
print(persona)



{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima', 'profesion': 'Ingeniera'}


In [12]:
# Eliminar un par clave-valor
del persona['ciudad']
print(persona)

{'nombre': 'Ana', 'edad': 30, 'profesion': 'Ingeniera'}


### Ejemplo 1.2: Métodos Útiles de Diccionarios


In [13]:
# Obtener todas las claves
print(persona.keys())


dict_keys(['nombre', 'edad', 'profesion'])


In [14]:
# Obtener todos los valores
print(persona.values())


dict_values(['Ana', 30, 'Ingeniera'])


In [15]:
# Comprobar si una clave existe en el diccionario
if 'edad' in persona:
    print("La clave 'edad' está en el diccionario.")


La clave 'edad' está en el diccionario.


### Ejercicio 1: Trabajando con Diccionarios

- Crea un diccionario que contenga información sobre un automóvil (marca, modelo, año, color).
- Accede a cada valor usando su clave.
- Añade una clave para el precio del automóvil.
- Elimina la clave del color del automóvil y muestra el diccionario actualizado.
- Usa keys() y values() para imprimir las claves y valores del diccionario.



In [20]:
auto = {"marca":"ford","modelo":"Mustang","year":"2023","color":"blanco"}
auto["precio"]= "$:/30.000"
print(auto["marca"])
print(auto)
print(auto.keys())
print(auto.values())


ford
{'marca': 'ford', 'modelo': 'Mustang', 'year': '2023', 'color': 'blanco', 'precio': '$:/30.000'}
dict_keys(['marca', 'modelo', 'year', 'color', 'precio'])
dict_values(['ford', 'Mustang', '2023', 'blanco', '$:/30.000'])


## 2. Sets

Los sets son colecciones de elementos únicos y desordenados. Son útiles para eliminar duplicados o realizar operaciones matemáticas como intersección y unión.

### Ejemplo 2.1: Creación y Modificación de Sets

In [21]:
# Crear un set
numeros = {1, 2, 3, 4, 5}
print(numeros)


{1, 2, 3, 4, 5}


In [26]:
# Añadir elementos

numeros.add("4")
print(numeros)


{1, 2, '6', 4, 5, 6, '4'}


In [28]:
# Eliminar un elemento
numeros.remove("6")
print(numeros)


{1, 2, 5, 6, '4'}


### Ejemplo 2.2: Operaciones de Conjuntos


In [29]:
# Crear otro set
otro_set = {4, 5, 6, 7}

In [32]:
# Unión de sets (todos los elementos)
nuevo = numeros.union(otro_set)
print("Unión:", nuevo)


Unión: {1, 2, 4, 5, 6, '4', 7}


In [33]:
# Intersección de sets (elementos comunes)
interseccion = numeros.intersection(otro_set)
print("Intersección:", interseccion)


Intersección: {5, 6}


### Ejercicio 2: Operaciones con Sets

- Crea dos sets de números: uno con números del 1 al 10 y otro con números del 5 al 15.
- Encuentra la intersección y unión de ambos sets.
- Elimina un número del primer set.
- Usa un set para almacenar los nombres de tus amigos. Asegúrate de que no haya duplicados.

In [44]:
set1 = set(range(1, 11))
set2 = set(range(1,16))
friend = {"marcelo","lucciano"}
set1.remove(1)
print(set1.union(set2))
print(set1.intersection(set2))


{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}
{2, 3, 4, 5, 6, 7, 8, 9, 10}


## 3. Matrices

En Python, las matrices pueden representarse como listas de listas. Para manipular matrices más avanzadas y realizar cálculos eficientes, utilizamos la librería NumPy.

### Ejemplo 3.1: Matrices con Listas de Listas


In [45]:
# Crear una matriz 3x3 con listas anidadas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matriz)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [9]:
# Acceder a elementos de la matriz
print("Elemento en [1][1]:", matriz[1][1])


Elemento en [1][1]: 5


In [47]:
# Modificar un elemento
matriz[2][0] = 10
print(matriz)

[[1, 2, 3], [4, 5, 6], [10, 8, 9]]


### Ejemplo 3.2: Manipulación de Matrices con NumPy


In [4]:
import numpy as np

# Crear una matriz 3x3 con NumPy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matriz_np)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# Sumar 10 a cada elemento
print(matriz_np + 10)



[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [5]:
# Multiplicar cada elemento por 2
print(matriz_np * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Ejercicio 3: Operaciones con Matrices

- Crea una matriz 3x3 usando listas de listas.
- Modifica un valor de la matriz y muestra la matriz actualizada.
- Usa NumPy para crear una matriz 4x4 con números aleatorios enteros.
- Realiza una operación de suma con la matriz (suma 5 a cada elemento).
- Multiplica los elementos de la matriz por 2 usando NumPy.

In [29]:
import numpy as np
mat = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
mat_np = np.random.randint(0, 6, size=(4, 4))
# mat[2][2]='xD'
print(mat)
# print(mat_np)
valor_a_sumar = 5
for i in range(len(mat)):
    for j in range(len(mat[i])):
        mat[i][j] += valor_a_sumar
for fila in mat:
  print(fila)
# print(mat_np *2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[6, 7, 8]
[9, 10, 11]
[12, 13, 14]


## 4. Desafío


Eres el encargado de un almacén de productos electrónicos. Tienes un registro de ventas semanales para teléfonos, laptops y tabletas. Necesitas analizar las ventas para mejorar la gestión.

- Crea tres listas: una para teléfonos, otra para laptops y otra para tabletas con las ventas de cada día durante una semana.
- Usa slicing para obtener las ventas de los últimos 3 días de cada producto.
- Usa listas por comprensión para calcular el total de ventas de cada producto y el promedio de ventas diarias.
- Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5.

Instrucciones:
Usa sum() y len() para calcular el total de ventas y el promedio.
Clasifica las ventas usando listas por comprensión.

In [38]:
# prompt: Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5

ventas_telefonos = [3, 7, 2, 9, 5, 1, 6]
ventas_laptops = [1, 4, 6, 8, 2, 5, 3]
ventas_tabletas = [5, 2, 8, 1, 7, 4, 9]

ultimos_3_telefonos = ventas_telefonos[-3:]
ultimos_3_laptops = ventas_laptops[-3:]
ultimos_3_tabletas = ventas_tabletas[-3:]
print("Ventas de los últimos 3 días de teléfonos:", ultimos_3_telefonos)
print("Ventas de los últimos 3 días de laptops:", ultimos_3_laptops)
print("Ventas de los últimos 3 días de tabletas:", ultimos_3_tabletas)
# Calcular el total de ventas y el promedio para cada producto
total_telefonos = sum(ventas_telefonos)
promedio_telefonos = total_telefonos / len(ventas_telefonos)

total_laptops = sum(ventas_laptops)
promedio_laptops = total_laptops / len(ventas_laptops)

total_tabletas = sum(ventas_tabletas)
promedio_tabletas = total_tabletas / len(ventas_tabletas)

print("Total de ventas de telefonos:", total_telefonos)
print("Promedio de ventas de telefonos:", promedio_telefonos)
print("Total de ventas de laptops:", total_laptops)
print("Promedio de ventas de laptops:", promedio_laptops)
print("Total de ventas de tabletas:", total_tabletas)
print("Promedio de ventas de tabletas:", promedio_tabletas)
# Clasificar los productos en "ventas altas" o "ventas bajas"
clasificacion_productos = [
    ("Telefonos", "Ventas altas" if promedio_telefonos > 5 else "Ventas bajas"),
    ("Laptops", "Ventas altas" if promedio_laptops > 5 else "Ventas bajas"),
    ("Tabletas", "Ventas altas" if promedio_tabletas > 5 else "Ventas bajas")
]

# Imprimir la clasificación
for producto, clasificacion in clasificacion_productos:
  print(f"{producto}: {clasificacion}")


Ventas de los últimos 3 días de teléfonos: [5, 1, 6]
Ventas de los últimos 3 días de laptops: [2, 5, 3]
Ventas de los últimos 3 días de tabletas: [7, 4, 9]
Total de ventas de telefonos: 33
Promedio de ventas de telefonos: 4.714285714285714
Total de ventas de laptops: 29
Promedio de ventas de laptops: 4.142857142857143
Total de ventas de tabletas: 36
Promedio de ventas de tabletas: 5.142857142857143
Telefonos: Ventas bajas
Laptops: Ventas bajas
Tabletas: Ventas altas


---

# Gracias por completar este laboratorio!

---